language: php

matrix:
 include:
  - os: windows
    language: sh
    before_install:
     - choco install php
     - choco install composer
     - choco install ffmpeg
     - export PATH="/c/tools/php73:/c/Program Files (x86)/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
  - os: linux
    php: '7.3'


addons:
 apt:
  packages:
   - ffmpeg

before_install:
 - bash -c 'echo $TRAVIS_OS_NAME'
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install php          ; fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install ffmpeg       ; fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install composer       ; fi

install:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then php "C:\Program Files (x86)\ComposerSetup\bin\composer.phar" --no-interaction;
  else composer install --no-interaction;
  fi


before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash); fi