language: php

matrix:
 include:
  - os: windows
    language: sh
    before_install:
     - choco install php
     - choco install composer
     - choco install ffmpeg
     - export PATH="/c/tools/php73:/c/ProgramData/ComposerSetup/bin/:/c/ProgramData/chocolatey/lib/ffmpeg/tools:$PATH"
     - cp tests/php-test.ini /c/tools/php73/php.ini
  - os: linux
    php: '7.3'


addons:
 apt:
  packages:
   - ffmpeg

before_install:
 - bash -c 'echo $TRAVIS_OS_NAME'

install:
 - composer install --no-interaction;

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash); fi