language: php
php:
 - '7.1'
 - '7.2'
 - '7.3'
 - '7.4'
 - '8.0'

matrix:
 include:
  - os: windows
    language: shell
    before_install:
     - choco install --no-progress tests/packages.config
     - export PATH="/c/tools/php80:/c/ProgramData/ComposerSetup/bin/:$PATH"
     - cp tests/php-test.ini /c/tools/php80/php.ini
  - os: linux
    php: '7.3'
  - php: '5.6'
    before_script:
     - sed "s/. void//" --in-place tests/filesTest.php
  - php: '7.0'
    before_script:
     - sed "s/. void//" --in-place tests/filesTest.php
  - php: 'nightly'
    install:
     - composer install --no-interaction --ignore-platform-reqs;
  - php: '7.4'
    name: 'Prefer lowest'
    install:
     - composer install --no-interaction
     - composer update --prefer-lowest

 allow_failures:
  - php: '5.6'
  - php: 'nightly'

addons:
 apt:
  packages:
   - ffmpeg

before_install:
 - bash -c 'echo $TRAVIS_OS_NAME'

install:
 - composer install --no-interaction;

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
 - bash <(curl -s https://codecov.io/bash)